### ISSUE TITLE
Error running colab 

### ISSUE THREAD

**Issue by rluceac** [googlecolab/colabtools#1074]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When I click run cell, got this:

Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page
- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
In chrome and firefox
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by tnovikoff** [comment]
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser. 

Logging into your Google account and enabling third-party cookies in your browser should resolve the issue.

**Comment by ncduy0303** [comment]
Hi, I still have the same issue with my Google Colab. I'm unable to execute any cells and after waiting a while, it displays this error: "Could not load the JavaScript files needed to display output.
This is probably because your Google Account login access has expired or because third-party cookies are not allowed by your browser."

However, I am pretty sure that my Google Account login access is not expired and my browser (Google Chrome) allows third-party cookies. I have tried restarting my browser, restarting my computer, logging in using incognito mode, checking the browser's task manager but none of these methods have worked for me.

**Comment by tnovikoff** [comment]
This may be relevant:
https://stackoverflow.com/questions/50289535/allow-a-google-colab-domain-cookies-on-chrome

**Comment by ncduy0303** [comment]
Hi, I have tried that method but it doesn't work for me either. After trial
and error, I think the problem is because of my dormitory wi-fi connection
or something (I cannot use Google Colab using other laptops or other
internet browsers), it works normally when I switch to using mobile
personal data as hotspot.
