### ISSUE TITLE
Unable to Copy/Cut/Paste Cell Contents in any browser with external keyboard on iPadOS 13.4

### ISSUE THREAD

**Issue by matthewcmead** [googlecolab/colabtools#1086]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Using any browser (have tried Safari, Brave, Chrome, Firefox) on iPadOS 13.4 with an external keyboard, using command-c (copy), command-x (cut) or command-v (paste) does not actually perform the action of copy/cut/paste.  Using the right-click context menu for “copy selection” also does not perform the action of copy.

- Describe the expected behavior:

command-c/command-x/command-v keyboard shortcuts for copy/cut/paste, and right-click context menus for the same would interact as expected with the copy/paste buffer.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Safari, Chrome, Firefox, Brave, all on iPadOS 13.4

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

Issue is exhibited on ALL notebooks.

**Comment by amon1024** [comment]
Same issue here,
iPadOS 13.5
iPad Pro 12.9 (3rd Gen) with Smart Keyboard Folio
Safari

Unable to copy anything within colab, but able to paste content from other pages or apps.

**Comment by sumitwaghmare** [comment]
Agreed. I have same issue. It’s frustrating

**Comment by eanappi** [comment]
I have the same problem

**Comment by eanappi** [comment]
I know it is not a solution, but if you have an external keyboard on the iPad OS 14, with your finger while it is not in edit mode, you can select and without removing your finger, press Cmd + c on the keyboard to copy.

**Comment by eanappi** [comment]
You can configure in COLAB the key configuration for VIM, and that is how everything works perfectly.

![970343F1-E7BA-4006-B35C-4F01E05F67E2](https://user-images.githubusercontent.com/1181227/95598710-a482c280-0a26-11eb-9a47-1c816316336f.jpeg)

**Comment by fallfromcloud** [comment]
Issue continues in iPadOS 14.4 with iPad 8th Gen

**Comment by flavourabbit** [comment]
The issues still continues

**Comment by pedronesbr** [comment]
The issue still continues

**Comment by JustinWNicholson** [comment]
Still a problem

**Comment by ArturoSbr** [comment]
The issue seems to have been solved.

**Comment by Sk-Azraf-Sami** [comment]
I still face this same problem. But after clearing my website cache, `ctrl+c' and `ctrl+v` work fine.

**Comment by Domiii** [comment]
This also affects Linux. I cannot copy/paste cell contents on Ubuntu 22.04.
