### ISSUE TITLE
Known issue: errors reading files from Drive

### ISSUE THREAD

**Issue by craigcitro** [googlecolab/colabtools#1428]
Colab is currently seeing elevated error rates for all Drive operations, in particular reading files.

This is a tracking issue; no need to +1 or "me too", we're working on it, and will update here as we have information.

**Comment by Smankusors** [comment]
I will give a little hint why this happens, exec this on your notebook

```
!cat /root/.config/Google/DriveFS/Logs/drive_fs.txt
```

And you see there's message about `QUOTA_EXCEEDED`. Welp RIP quota.

**Comment by seanggggggg** [comment]
> message a
Do you know how to solve this? I encountered the same problem while trying to load a 500MB csv file using pd.read_csv on Google Colab

**Comment by saransh09** [comment]
> I will give a little hint why this happens, exec this on your notebook
> 
> ```
> !cat /root/.config/Google/DriveFS/Logs/drive_fs.txt
> ```
> 
> And you see there's message about `QUOTA_EXCEEDED`. Welp RIP quota.

Does that quota also hold for uploading to the google drive? I can live with not being able to download files from Google Drive for some time, but not being able to upload the the drive, that is a killer.

**Comment by farhadinima75** [comment]
thanks @craigcitro ...
we all waiting for your solutions

**Comment by Smankusors** [comment]
> > I will give a little hint why this happens, exec this on your notebook
> > ```
> > !cat /root/.config/Google/DriveFS/Logs/drive_fs.txt
> > ```
> > 
> > 
> > And you see there's message about `QUOTA_EXCEEDED`. Welp RIP quota.
> 
> Does that quota also hold for uploading to the google drive? I can live with not being able to download files from Google Drive for some time, but not being able to upload the the drive, that is a killer.

it's seems no. But if there's existing file, you need to delete it first.

**Comment by saransh09** [comment]
> > > I will give a little hint why this happens, exec this on your notebook
> > > ```
> > > !cat /root/.config/Google/DriveFS/Logs/drive_fs.txt
> > > ```
> > > 
> > > 
> > > And you see there's message about `QUOTA_EXCEEDED`. Welp RIP quota.
> > 
> > 
> > Does that quota also hold for uploading to the google drive? I can live with not being able to download files from Google Drive for some time, but not being able to upload the the drive, that is a killer.
> 
> it's seems no. But if there's existing file, you need to delete it first.

RIP training a model and saving weights in the google drive.

**Comment by seanggggggg** [comment]
> > > > I will give a little hint why this happens, exec this on your notebook
> > > > ```
> > > > !cat /root/.config/Google/DriveFS/Logs/drive_fs.txt
> > > > ```
> > > > 
> > > > 
> > > > And you see there's message about `QUOTA_EXCEEDED`. Welp RIP quota.
> > > 
> > > 
> > > Does that quota also hold for uploading to the google drive? I can live with not being able to download files from Google Drive for some time, but not being able to upload the the drive, that is a killer.
> > 
> > 
> > it's seems no. But if there's existing file, you need to delete it first.
> 
> RIP training a model and saving weights in the google drive.

What do you mean? You mean we need to delete the existing files on Google Drive to have it be reused again in the future?

**Comment by Smankusors** [comment]
> What do you mean? You mean we need to delete the existing files on Google Drive to have it be reused again in the future?

no no, I mean if you want to write, for example file "A", you want to save it to `/content/drive/My Drive/some folder` but there's already exist a file with filename `/content/drive/My Drive/some folder/A`.

If you want to update this file, I think you need to delete it first and then you saved it. For some reason on this outage you can't overwrite existing files.

But my advice is, avoid using Drive for now until Google solved this. We don't know if it causes corruption or something else.

**Comment by farhadinima75** [comment]
this error is showing to me when I want to read files from Drive:

OSError: [Errno 5] Input/output error

**Comment by Modulariti** [comment]
I run into the same problem, simply copying small text file does not work:

%cp "drive/My Drive/Download/test.txt" .

cp: error reading 'drive/My Drive/Download/test.txt': Input/output error

**Comment by anoopkdcs** [comment]
I'm also run into the same problem while reading files (both small and large in size) from GDrive to Colab.

**Comment by saransh09** [comment]
> I'm also run into the same problem while reading files (both small and large in size) from GDrive to Colab.

Yes, as they have already reported google is facing some issues with the GDrive integration with Colab. Let's just wait for them to fix it. Till then, just create a sharable link of the files that you want and then wget them to your instance.

**Comment by craigcitro** [comment]
This should be fixed, and Drive access from Colab should be back in working order.

**Comment by saransh09** [comment]
> This should be fixed, and Drive access from Colab should be back in working order.

Yes, it is fixed. Thanks for the update.

**Comment by Leggerla** [comment]
Hi! Colab still gives this error for me. Always with GPU, often but not always with runtime type = None.

**Comment by raynt** [comment]
I'm still having the OSError: [Errno 5] Input/output issue. Everything will be working fine, get the error then locked out from continuing training. The only things that seems to work is waiting and come back a day later. How do we check to see if we have gone over the bandwidth limit, (if there is one?, it is very unclear why this is happening).

**Comment by alexanderwhatley** [comment]
Still happening for me too on Colab Pro....

**Comment by tooHotSpot** [comment]
The issue is not fixed and is still happening with Colab Pro and Google One Subscription for datasets storage.

**Comment by NicholasLaur** [comment]
I have now the same problem.

**Comment by zectre** [comment]
I get this problem now

**Comment by jianmosier** [comment]
I still have the OSError. It triggered by os.listdir(FILE_PATH). And the file only 500MB, but have 80000 JPG. And I have read it successful yesterday.

**Comment by kithogue** [comment]
Hello, I don't know if you know about it, but part of my data is partially lost (i. e. parts of strings) when I'm trying to read the data from drive to a dataframe in colab notebook. Besides, the data is deserialized as strings instead of any other type of data, which never happened to me in a jupyter notebook.
