### ISSUE TITLE
return key

### ISSUE THREAD

**Issue by hmkam** [googlecolab/colabtools#1628]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by hmkam** [comment]
when I run the colab python program in the chrome browser of my android phone. It seems that the program cannot read the return key from the sofware keyboard of my phone.

**Comment by colaboratory-team** [comment]
Thanks for the report. Tracked internally as b/170359363.

**Comment by colaboratory-team** [comment]
Should be fixed if you reload the colab tab.

**Comment by richaardvark** [comment]
This is still not fixed. It does not matter what Android browser I use nor does it matter what keyboard I use nor does it matter if Colab is viewed as desktop view or mobile view - it is not possible to press the return key during the execution of code. It is registered as a next/tab press instead of return / enter function. It was working for a long time but about 4 or 5 months ago stopped functioning properly again. There are multiple other issue tickets on here where people are having the same issue. If you search for "enter key"  or "return key"  you will find others experiencing the same problem. 
![Screenshot_2022-10-05-14-04-12-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41244847/194143466-360cc758-a415-4680-9d26-b4c3072f2055.jpg)

**Comment by richaardvark** [comment]
Please see #1683

**Comment by gjkendall** [comment]
The actual problem is that gboard (and I guess all other keyboards) change the behavior of the key to TAB when they are in a text box (form input).  That arrow and bar is the tab input. Colab is responding to tab to go to the next box down when ends up in the code box below the input.  Colab never gets the input. This problem occurs with other programs/app that use gboard and other virtual keyboards. Colab should see that the input needs to be accepted even if it ends in a tab and gboard and other virtual keyboards need a way to press a return button when necessary.  The return button is that button that has a bent arrow that goes down and then to the left. There should be separate tab keys and return keys on gboard and the other virtual keyboards. As it is now I can't get input into colab from an android device unless I hard code it. PLEASE FIX THIS ELEMENTARY AND FUNDAMENTAL BUG!

**Comment by richaardvark** [comment]
> The actual problem is that gboard (and I guess all other keyboards) change the behavior of the key to TAB when they are in a text box (form input). That arrow and bar is the tab input. Colab is responding to tab to go to the next box down when ends up in the code box below the input. Colab never gets the input. This problem occurs with other programs/app that use gboard and other virtual keyboards. Colab should see that the input needs to be accepted even if it ends in a tab and gboard and other virtual keyboards need a way to press a return button when necessary. The return button is that button that has a bent arrow that goes down and then to the left. There should be separate tab keys and return keys on gboard and the other virtual keyboards. As it is now I can't get input into colab from an android device unless I hard code it. PLEASE FIX THIS ELEMENTARY AND FUNDAMENTAL BUG!

I mean we're all aware of what's going on here or we wouldn't be in this situation. That is why we found a workaround. There are many elementary and fundamental bugs in many Google products but it doesn't mean anything is going to be resolved. And this may be bigger than Colab but might just be a limitation of Android and the way that input devices are detected via text input fields.

**Comment by rsemenoff** [comment]
Seems like a simple fix to create a subclass of input boxes for colab, and have gboard simply recognize that class. What is that, like 2 lines of code?
