### ISSUE TITLE
unable to use colab, Error popup is displaying

### ISSUE THREAD

**Issue by MallikarjunNamagiri** [googlecolab/colabtools#17]
Hi,
I am unable to use the colb, while trying to open it is giving below error as 
"NotSupportedError: Failed to register a ServiceWorker: The user denied permission to use Service Worker."

While using below code getting error.
#Uploading the Dataset 
from google.colab import files
uploaded = files.upload()

Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable.

Thanks in Advance.

Regards,
Mallikarjun
![colb error](https://user-images.githubusercontent.com/30703513/34467575-05389704-ef1c-11e7-8c5d-6b7121a129e6.PNG)

**Comment by blois** [comment]
Can you try opening Colab in a Chrome incognito window? Or if that doesn’t
work, then possibly try FireFox.

I’m trying to track down what causes this error- it’s quite rare.

**Comment by MallikarjunNamagiri** [comment]
Hi Blois,
Thanks for your response.

I tried to run the same in Chrome Incognito window, but issue is same.
The same code is working in the other network and able to upload the files too. But in my home network its not coding by using Chrome and Mozilla Firefox browsers.

Please find the below code i'm using and error details
#Uploading the Dataset 
from google.colab import files
uploaded = files.upload()

#Save uploaded file on the Virtual Machine's 

with open("train.csv", 'w') as f:
    f.write(uploaded[uploaded.keys()[0]])
-------------------------------------------------------
error:
Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable.
---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
<ipython-input-11-12c5d4ce48c9> in <module>()
----> 1 uploaded = files.upload()
      2 
      3 for fn in uploaded.keys():
      4   print('User uploaded file "{name}" with length {length} bytes'.format(
      5       name=fn, length=len(uploaded[fn])))

/usr/local/lib/python3.6/dist-packages/google/colab/files.py in upload()
     59   result = output.eval_js(
     60       'google.colab._files._uploadFiles("{input_id}", "{output_id}")'.format(
---> 61           input_id=input_id, output_id=output_id))
     62   files = collections.defaultdict(six.binary_type)
     63 

/usr/local/lib/python3.6/dist-packages/google/colab/output/_js.py in eval_js(script, ignore_result)
     33   if ignore_result:
     34     return
---> 35   return _message.read_reply_from_input(request_id)

/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
     84         reply.get('colab_msg_id') == message_id):
     85       if 'error' in reply:
---> 86         raise MessageError(reply['error'])
     87       return reply.get('data', None)
     88 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

Thanks in advance.

Regards,
Mallikarjun.N

**Comment by blois** [comment]
The error with files.upload() is because it requires the browser's ServiceWorker API to function correctly. I'm trying to understand why Service Workers appear to not be working for you- normally they are only disabled when third-party cookies are disabled. I'd be curious if you happen to have any non-standard cookies settings in chrome://settings/content/cookies?

I appreciate the help tracking this down!

**Comment by MallikarjunNamagiri** [comment]
Hi Blois,

Issue got resolved by disabled to cookies settings as 'Block third-party cookies'.

Thanks for your support.

Regards,
Mallikarjun.N

**Comment by R1j1t** [comment]
I am still facing the same issue. As mentioned that enabling 3rd part cookies will resolve the same, but not for me. I am using firefox 59.0.1 (64-bit). I am adding colab file [here](https://drive.google.com/file/d/1B4a-6oLi0xv_MkGazCPdkVjPwndPTb5D/view?usp=sharing).
-Rajat

**Comment by MallikarjunNamagiri** [comment]
Hello R1j1t,

For me still it's working by disabling the 3rd Party Cookies.

Please find the below screenshot for better understanding.

![cookies](https://user-images.githubusercontent.com/30703513/37720228-dbc73d84-2d4c-11e8-85a6-37e7e8f72569.PNG)

Regards,
Mallikarjun.N

**Comment by blois** [comment]
Fixes for FireFox 59 will be arriving soon, we ran into https://bugzilla.mozilla.org/show_bug.cgi?id=1446225.

**Comment by AleHRejon** [comment]
I solved it using Google Chrome

**Comment by morriswong** [comment]
I would like to keep the `Block third party cookies` settings to be turned on at all times for the sake of our privacy. Currently I will have to have another tab by the so that after I have finished using colab, I can turn it off right away and not to forget it. BUT I would have to do it every time I use colab.

To solve this, I have tried to add `https://colab.research.google.com` and `[*.]google.com` to the Allow whitelist on Cookies, but then the error pop up would still show. I also tried `https://colab.research.google.com[/*]`, but chrome said its not a vaild domain.

Is there a way to whitelist colab domain for that??

**Comment by andreagrandi** [comment]
@blois I'm using Firefox 60 and I'm still having this exact problem

**Comment by yychan76** [comment]
I tried whitelisting in chrome the following
`https://[*.]googleusercontent.com:443`

Seems to work.

**Comment by alxfed** [comment]
And __*why*__ do we all have to enable the sh..ty 'third party cookies', may I ask?

**Comment by blois** [comment]
The third party cookies stems from Colab's use of [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) within iframes hosted on separate origins (the *-colab.googleusercontent.com domain). The service workers are used to allow rich outputs to communicate directly to the runtime and also to allow those outputs to continue to work when viewed later.

The Service Workers are tied to third-party cookies by the browser: https://dev.chromium.org/Home/chromium-security/security-faq/service-worker-security-faq#TOC-Can-iframes-register-Service-Workers-

Most outputs will continue to work without these enabled. Colab should only prompt once on startup for this then make a best-effort to continue, but some visualizations may not work.

**Comment by nanbaima** [comment]
> I tried whitelisting in chrome the following
> `https://[*.]googleusercontent.com:443`
> 
> Seems to work.

Best answare ever!

**Comment by alxfed** [comment]
Best answer? You will answer for _**not**_ blocking google, doubleclick and other sh...tty tracking cookies in Chromium when the user explicitly blocks them... some day. That will be the best answer. My guess in will be in a court hearing.

**Comment by vishwanath63** [comment]
> Hi Blois,
> 
> Issue got resolved by disabled to cookies settings as 'Block third-party cookies'.
> 
> Thanks for your support.
> 
> Regards,
> Mallikarjun.N

ya it's working
thank you

**Comment by Dodger23** [comment]
I disabled 'Block third-party cookies'
 
![image](https://user-images.githubusercontent.com/60031675/84551927-6d6a0200-ad0f-11ea-8528-81d3b8cbfb17.png)

and added 'https://[*.]googleusercontent.com:443' to Allow 
![image](https://user-images.githubusercontent.com/60031675/84551938-7a86f100-ad0f-11ea-8156-7b79b394e093.png)

Still the same Error

**Comment by blois** [comment]
This may also occur if outputs are being displayed which are consuming 100% of your CPU- you can see this in Chrome's Task Manager. Killing the task in task manager or restarting Chrome may fix the issue.

**Comment by Dodger23** [comment]
@blois  thanks, I did as you told and that was the exactly the problem.

**Comment by Emekaborisama** [comment]
> This may also occur if outputs are being displayed which are consuming 100% of your CPU- you can see this in Chrome's Task Manager. Killing the task in task manager or restarting Chrome may fix the issue.

but i need the output

**Comment by blois** [comment]
Typically this occurs if the output is too large or includes code which is consuming too much CPU.

**Comment by mzahran001** [comment]
I'm working on Chrome Version 84.0.4147.105 (Official Build) (64-bit) on Mac OS

Added 'https://[*.]googleusercontent.com:443' to Allow

Still the same error when running any commend that is printing any word.

**Comment by blackwarriorxtn** [comment]
While Using **Brave** Turn off shield to solve this issue

**Comment by blackwarriorxtn** [comment]
Also make sure you're not using any Tracker Blocker or third party plugin that is blocking scripts
