### ISSUE TITLE
Google colab running on GPU reporting `CUDA error: no kernel image is available for execution on the device`

### ISSUE THREAD

**Issue by JoanFM** [googlecolab/colabtools#2670]
The same colab was running days ago and today this is being reported.

CUDA error: no kernel image is available for execution on the device

**Comment by cperry-goog** [comment]
This should be fixed now, see #2088

**Comment by orkenstein** [comment]
I experience the same on Premium GPU. Works fine with Standard.

**Comment by frytoli** [comment]
This is still an issue for me as well; only with the A100 GPUs.

**Comment by oradrok** [comment]
@orkenstein Same here. Any update/solution on this?

**Comment by orkenstein** [comment]
> @orkenstein Same here. Any update/solution on this?

Ended up using premium GPUs
