### ISSUE TITLE
IPython.display.Markdown doesn’t work

### ISSUE THREAD

**Issue by natewind** [googlecolab/colabtools#322]
mybinder.org or locally installed Jupyter Notebook:
![image](https://user-images.githubusercontent.com/30814650/47495331-87b24c00-d85c-11e8-9e6c-3a9b07738a0b.png)

Colaboratory:
![image](https://user-images.githubusercontent.com/30814650/47495382-aca6bf00-d85c-11e8-9a8b-5c8629a80575.png)

**Comment by blois** [comment]
Currently Colab does not natively support markdown in outputs, will take this as a feature request.

**Comment by WittmannF** [comment]
Any update @blois ?

**Comment by blois** [comment]
No progress but we'll take this into further consideration. There are actually two issues here- markdown and LaTeX processing. See https://github.com/googlecolab/colabtools/issues/594 for more details on the LaTeX issue.

**Comment by dsposito** [comment]
+1

**Comment by versae** [comment]
As a workaround, I replaced `IPython.disaply.Markdown` with a function that makes use of [`markdown`](https://python-markdown.github.io/):
```python
!pip install markdown
import IPython
from markdown import markdown
Markdown = lambda string: IPython.display.HTML(markdown(string))

Markdown("# *test*")
```
It works fine for Markdown. For LaTeX, an extension must be used and the code gets a bit more messy:
First, a cell registering a `pre_run_cell` event so MathJax can be loaded:
```python
from IPython.display import Math, HTML

def load_mathjax_in_cell_output():
  display(HTML("<script src='https://www.gstatic.com/external_hosted/"
               "mathjax/latest/MathJax.js?config=default'></script>"))
get_ipython().events.register('pre_run_cell', load_mathjax_in_cell_output)
```
Then the definition of our function:
```python
!pip install markdown python-markdown-math
import IPython
import markdown as md
import mdx_math

Markdown = lambda string: IPython.display.HTML(
    md.markdown(string, extensions=[mdx_math.MathExtension(enable_dollar_delimiter=True)])
)

Markdown("*test* $e^3$")
```

**Comment by blois** [comment]
This should now be working.

**Comment by versae** [comment]
Still not working for me
![image](https://user-images.githubusercontent.com/173537/83555619-cfa45500-a50e-11ea-86e8-41ee80e47b29.png)
Is this something that will be rolled out on an incremental basis?

**Comment by blois** [comment]
Perhaps try a page reload (shift-reload to skip cache)?

**Comment by versae** [comment]
Awesome!
![image](https://user-images.githubusercontent.com/173537/83558345-30ce2780-a513-11ea-91c9-c6c5d391920d.png)
Many thanks
