### ISSUE TITLE
Support installation of custom widgets.

### ISSUE THREAD

**Issue by blois** [googlecolab/colabtools#498]
Currently Colab only supports the widgets included in the ipywidgets package and does not allow installing additional widgets.

Additional background is available at https://github.com/nteract/nes/tree/master/portable-widgets.

**Comment by korakot** [comment]
[Qgrid](https://github.com/quantopian/qgrid) would make it easier to work with pandas dataframe.

Hope it will be supported in the future.

**Comment by cornhundred** [comment]
We're building a custom widget called Clustergrammer2 that is a webgl DataFrame viewer and is currently supported on Kaggle https://www.kaggle.com/cornhundred/heatmap-view-of-modern-era-player-stats

**Comment by blois** [comment]
Glancing at the widget code in https://github.com/ismms-himc/clustergrammer2/blob/5acea9bff7eda546cf0647b9e3647f631eb6f5f5/clustergrammer2/clustergrammer_fun/__init__.py#L222, it doesn't seem like it's making much use of the Widgets API, specifically comms messages.

A quick example of your (very slick) notebook running in Colab, with the visualizations:
https://colab.sandbox.google.com/gist/blois/dd01cd63d199acca951aadefb22067a8/heatmap-view-of-modern-era-player-stats.ipynb

**Comment by cornhundred** [comment]
Thanks @blois, in order to run the notebook you sent I had to add the Seasons_Stats.csv (from here https://www.kaggle.com/drgilermo/nba-players-stats) to the filesystem. However, I did not see the interactive visualization. 

cc @manugarciaquismondo

**Comment by blois** [comment]
@korakot we recently added an interactive dataframe viewer that we've been using internally for ages.

You can enable it by default with:
```python
%load_ext google.colab.data_table
from vega_datasets import data
data.cars()
```

Or use it on a per-dataframe basis:
```python
from google.colab.data_table import DataTable
from vega_datasets import data
DataTable(data.cars())
```

**Comment by korakot** [comment]
@blois Thanks a lot. It will surely help.

BTW, is there a widget to edit the dataframe as well?

And what other `%load_ext` are available? Is there a list somewhere?

**Comment by Kreijstal** [comment]
can you install custom widgets now?

**Comment by Location-Artistry** [comment]
This problem still persists with Google Colab on August 13th, 2020.
ArcGIS Python API maps will not display.
All the other portions of the API seem to work great in Colab, and I am able to conduct ArcGIS Online Admin from Colab.
Currently switching over to the AGOL Jupyter Notebook interface to view the map widget display.
Perhaps there could be a clever workaround by exporting to html or viewing as JavaScript.

**Comment by giswqs** [comment]
@blois Please add support for [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet), which would make visualizing and interacting Google Earth Engine tile layers much easier with the earthengine-api. @tylere @SylvainCorlay @martinRenou @davidbrochart

**Comment by jasonho-lynx** [comment]
Hi, let me know if this isn't the right place - it would be great to have support for [pymotif](https://github.com/cylynx/motif.gl/tree/master/packages/pymotif), which is a Jupyter widget for [Motif](https://github.com/cylynx/motif.gl), a no-code graph visualization platform. Thank you! @timlrx

**Comment by ucalyptus** [comment]
@blois any updates on this?

**Comment by Berowne** [comment]
> [Qgrid](https://github.com/quantopian/qgrid) would make it easier to work with pandas dataframe.
> 
> Hope it will be supported in the future.

+1 for QGRID

**Comment by blois** [comment]
We are working on this, some details of the proposal are in https://github.com/googlecolab/colab-cdn-widget-manager.

Right now the support can be experimented with by adding **to the cell displaying the widget**:
```python
from IPython.display import Javascript

display(Javascript('''
  google.colab.widgets.installCustomManager('https://ssl.gstatic.com/colaboratory-static/widgets/colab-cdn-widget-manager/6a14374f468a145a/manager.min.js');
'''))
```

This will remain opt-in but we plan to work on improving the mechanism.

Some examples:
 - ipyleaflet: https://colab.research.google.com/gist/blois/5b840e35d7fae2e10689c30708694de9/ipyleaflet.ipynb
 - ipympl: https://colab.research.google.com/gist/blois/ddec4e43a55e94d87a30cfe198d3cd50/ipympl.ipynb
 - qgrid: https://colab.research.google.com/gist/blois/3b36d0aa4c32d2ecc71e9208c32cf333/qgrid.ipynb

This specific widget manager version is tied to [@jupyter-widgets/base](https://www.npmjs.com/package/@jupyter-widgets/base) v5.0.0a so there may be some incompatibilities with with specific widget versions (https://github.com/bloomberg/ipydatagrid is known to be incompatible for example).

Please feel free to open specific bugs in https://github.com/googlecolab/colab-cdn-widget-manager/issues.

**Comment by giswqs** [comment]
@blois This is exciting!! Thank you so much for implementing this. It is a game-changer!!

**Comment by blois** [comment]
An update that the mechanism to opt-into this will be changing shortly to:

```python
from google.colab import output
output.enable_custom_widget_manager()
```

Which only needs to be executed once in the notebook to affect all later executions.

**Comment by giswqs** [comment]
@blois This is fantastic, making life much easier! When will it be released? Can't wait to try it out. 

![](https://i.imgur.com/A8RxoyS.png)

**Comment by blois** [comment]
@giswqs  Hopefully later today.

**Comment by giswqs** [comment]
@blois It is working now. I have integrated the following two lines into the [geemap](https://github.com/giswqs/geemap) and [leafmap](https://github.com/giswqs/leafmap/) packages so that users don't have to execute them explicitly. Now the same code can run seamlessly on both Colab and Jupyter without making any changes. I also created a pull request to update ipyleaflet https://github.com/jupyter-widgets/ipyleaflet/pull/869



```
from google.colab import output
output.enable_custom_widget_manager()
```

One issue I noticed is that the toolbar icon size (created using ipywidgets) is much bigger on Colab than on Jupyter notebook. I could not figure out why. 

Leafmap Colab example: https://colab.research.google.com/drive/1NSdDIkXxeD2tCVw38gQ7nLIvgdwOx20c

Colab:
![Screenshot_20210911_000403](https://user-images.githubusercontent.com/5016453/132935742-439e352f-0857-4f46-85c7-d557a63a972b.png)

Jupyter notebok
![Screenshot_20210911_000520](https://user-images.githubusercontent.com/5016453/132935746-4fc6db3e-5122-4aa1-8925-36e4d183b65a.png)

**Comment by kylebarron** [comment]
I'm excited that custom widgets is getting attention and a beta API exists. Unfortunately it appears that the current Colab widgets implementation is incomplete. Specifically Comm messages sent from following cells never arrive at widget views in previous outputs.

I took some time to create a minimal reproducible example of this, showing how the API works in JupyterLab and where it fails in Colab.

I created a new, very basic widget based on `ipywidgets` just for debugging: https://github.com/kylebarron/jupyter-widget-echo-testing. This uses the default [TypeScript Widget Cookiecutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter) with a couple modifications:

- On the JavaScript side, [send a message back to Python whenever the value of `value` changes](https://github.com/kylebarron/jupyter-widget-echo-testing/blob/4b5ea770e517b4b1f3a108570bfa6da3a7a39c72/src/widget.ts#L57)
- On the JavaScript side, [send a message back to Python whenever a custom message is received[(https://github.com/kylebarron/jupyter-widget-echo-testing/blob/4b5ea770e517b4b1f3a108570bfa6da3a7a39c72/src/widget.ts#L45)
- On the Python side, [record an array of messages received back from JavaScript](https://github.com/kylebarron/jupyter-widget-echo-testing/blob/4b5ea770e517b4b1f3a108570bfa6da3a7a39c72/jupyter_widget_echo_testing/example.py#L31-L36).

Then I created two notebooks, [one for use in Jupyter Notebook/Lab](https://github.com/kylebarron/jupyter-widget-echo-testing/blob/master/jupyter_example.ipynb) showing how I expect the widget implementation to work, and [one for use in Colab](https://github.com/kylebarron/jupyter-widget-echo-testing/blob/master/Colab_example.ipynb) showing where the implementation is incomplete. Here are direct links:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/kylebarron/jupyter-widget-echo-testing/master?labpath=jupyter_example.ipynb)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kylebarron/jupyter-widget-echo-testing/blob/master/Colab_example.ipynb)

Specifically, any messages after the initial cell fail to reach the JS code running in the original widget view. This means that it's hard (impossible?) for widget developers to support interactivity from Python to running JS code and severely limits what's possible to do with widgets in Colab.

**Comment by blois** [comment]
@kylebarron Thanks for the great report, will take a bit to dig into it.

Some tricks for future explorers in this area- you can define a 'custom widget manager' with a base64 URL which resolves to an ES6 module which implements this API- https://github.com/googlecolab/colabtools/blob/7c6e16b93f64fcc19926b7db0c6e2502ee11e1c2/packages/outputframe/lib/index.d.ts#L175.

A really simple example of this is https://colab.research.google.com/gist/blois/4d3125395020ed671599d90a0dcedefe/custom_widget_hack.ipynb.

Can also use Comms without using widgets, I think this example may expose the issue you mentioned-
https://colab.research.google.com/gist/blois/3fe2426b2aef36f55d5370e496fec736/comms.ipynb

**Comment by shadiakiki1986** [comment]
Is colab support for ipywidgets Tab, Accordion, Stacked broken?

Example notebook: https://colab.research.google.com/drive/1rYNEUyGHGufYmrDRGMWZLsTuQ-vVXG8T?usp=sharing

Related:
- https://github.com/googlecolab/colabtools/issues/60
- https://stackoverflow.com/questions/47269168/ipywidgets-with-google-colaboratory#48920438

**Comment by blois** [comment]
@shadiakiki1986 Added details in the jupyter-widgets bug, I believe that Colab is matching JupyterLab behavior when custom widget support is enabled.

**Comment by shadiakiki1986** [comment]
@blois What about Tab and Accordion?

**Comment by blois** [comment]
@kylebarron The fix for your issue should be live now.

**Comment by cardinalgeo** [comment]
@blois it seems that custom widgets still aren't working with Plotly. I've implemented [this example](https://plotly.com/python/figurewidget-app/) from the Plotly website in Colab [here](https://colab.research.google.com/drive/1s-BUdZt_frp3OIe_P40abevDxy3QPbFU?usp=sharing). While the widgets appear, the plot itself does not. Do you have any idea why this might be the case?

**Comment by kylebarron** [comment]
The plot appears for me when you call `g.show()` in a cell. Though the message passing doesn't appear to work immediately for me.

**Comment by cardinalgeo** [comment]
@kylebarron I had also tried `g.show()` but haven't gotten the message passing to work.

**Comment by kylebarron** [comment]
Possibly relevant; Plotly has a weird way of sending messages between Python and JS. https://github.com/plotly/plotly.py/blob/df19fc702b309586cc24e25373b87e8bdbb3ff60/packages/python/plotly/plotly/basewidget.py#L52-L101

> These properties are used to send messages from Python to the frontend. Messages are sent by assigning the message contents to the appropriate `_py2js_*` property and then immediatly assigning `None` to the property.

Instead of using something like `widget.send()` for a custom message. You could probably debug within Colab to see when you set a Python attribute if that changes on the JS side or not, and vice versa.

**Comment by JesseFarebro** [comment]
@kylebarron I tried debugging this and the messages are passed without issue. It seems the proper commands are sent to plotly but nothing is being displayed. It would be really nice to have this working in Colab.

**Comment by kylebarron** [comment]
> The plot appears for me when you call `g.show()` in a cell. Though the message passing doesn't appear to work immediately for me.

Just noting that I was wrong here. The Plotly `FigureWidget` [subclasses from both `BaseFigure` and `widgets.DOMWidget`](https://github.com/plotly/plotly.py/blob/df19fc702b309586cc24e25373b87e8bdbb3ff60/packages/python/plotly/plotly/basewidget.py#L20). The `.show()` comes from `BaseFigure`, so when you call `.show` it's rendering a static HTML output without touching the widget machinery at all. When you render the widget directly in a cell, i.e.

```py
from google.colab import output
output.enable_custom_widget_manager()

import plotly.graph_objects as go
f = go.FigureWidget(layout={'height': 400, 'width': 400})
f
```
if you look in the network tab the right plotly widget bundle gets downloaded (`plotlywidget` for plotly v4 and `jupyterlab-plotly` for plotly v5). I'm guessing there's some sort of bad interaction with Colab's widget manager but it's hard to tell.

**Comment by blois** [comment]
@kylebarron @JesseFarebro Details on the Plotly issue are in https://github.com/googlecolab/colab-cdn-widget-manager/issues/19.

**Comment by cardinalgeo** [comment]
Thanks for taking a look at this @kylebarron @JesseFarebro, and thanks for the quick fix @blois—I'm looking forward to seeing it go live!

**Comment by blois** [comment]
@cardinalgeo your example should now be working, see https://github.com/googlecolab/colab-cdn-widget-manager/issues/19#issuecomment-978171175.

**Comment by cardinalgeo** [comment]
Thanks @Blois! However, the example is unfortunately still not working. Running the block in the jupyter lab screenshot below should produce both the widgets and the plot. But running the same cell in colab only produces the widgets. I can run `g.show()` in a separate cell to display the plot, but, while the message passing seems to work, a change in the dropdown widgets only results in a change in the plot after re-running `g.show()`, which is not ideal. Do you have any idea why the widgets and figure aren't both being displayed in the output such that a change in the widget automatically produces a change in the figure? 
<img width="1123" alt="Screen Shot 2021-11-24 at 9 07 12 PM" src="https://user-images.githubusercontent.com/44422832/143367020-b846b6db-e9ee-4f43-bc6f-ef55c565d594.png">
?

**Comment by kylebarron** [comment]
From my comment here https://github.com/googlecolab/colabtools/issues/498#issuecomment-975863250

> The Plotly `FigureWidget` [subclasses from both `BaseFigure` and `widgets.DOMWidget`](https://github.com/plotly/plotly.py/blob/df19fc702b309586cc24e25373b87e8bdbb3ff60/packages/python/plotly/plotly/basewidget.py#L20). The `.show()` comes from `BaseFigure`, so when you call `.show` it's rendering a static HTML output without touching the widget machinery at all.

In order to render the widget and not the static HTML output mode, you need to render without `.show`. The below Colab notebook is a direct copy of [this page](https://plotly.com/python/figurewidget/) in the Plotly docs, adding only the command to enable custom widgets.

<a href="https://colab.research.google.com/gist/kylebarron/db3c3ce4011c244966a3979158e1ae0c/figurewidget.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here, the widget doesn't render, and I see this console error:
![image](https://user-images.githubusercontent.com/15164633/143923761-bb99b939-1722-4259-b050-567f003dfddb.png)

**Comment by lukewys** [comment]
> Here's an example for qgrid: https://colab.research.google.com/gist/blois/3b36d0aa4c32d2ecc71e9208c32cf333/qgrid.ipynb

For those who want to use `qgrid` in their Colab notebook but don't want to confuse people on colab force restart, I found a workaround for using `qgrid` without restarting the session.  The question is about `qgrid 1.1.1` not supporting pandas>1.0.0. You can fork `qgrid` to your own repo, roll back the version to 1.1.1, and change the code according to https://github.com/quantopian/qgrid/issues/287. Then, you could pip install via git from your repo.

For example, you can do `pip install git+https://github.com/lukewys/qgrid.git` (a fork of `qgrid` where I fixed this issue).

**Comment by tylere** [comment]
Please add support for the ipytree widget too: #2522

**Comment by cardinalgeo** [comment]
> 

@kylebarron thanks for the Plotly widget example! I can't find a way to view the console error (is it from terminal, which is only available with colab pro)?  Do you have any sense of whether this issue can be resolved on the Colab side or if it will require work on the Plotly side?

**Comment by cardinalgeo** [comment]
> Here, the widget doesn't render, and I see this console error:

@kylebarron thanks for the Plotly widget example! I can't find a way to view the console error (is it from terminal, which is only available with colab pro)? Do you have any sense of whether this issue can be resolved on the Colab side or if it will require work on the Plotly side?

**Comment by blois** [comment]
@cardinalgeo Support for the plotly widgets was tracked in https://github.com/googlecolab/colab-cdn-widget-manager/issues/19. There's a link to your example working in there.

**Comment by blois** [comment]
At this point installation of custom widgets are supported. This requires opting in by using the code:

```python
from google.colab import output
output.enable_custom_widget_manager()
```

Specific widgets may need additional investigation or tweaks. It's easiest to open individual issues for these investigations. Most of the bugs have been tracked in https://github.com/googlecolab/colab-cdn-widget-manager/issues?q=is%3Aissue.

**Comment by cardinalgeo** [comment]
Hi @blois, thanks for the follow up! However, the example still seems to not work. I'll continue this thread in googlecolab/colab-cdn-widget-manager#19

**Comment by martinRenou** [comment]
Thanks a lot for your work on this @blois !

**Comment by cornhundred** [comment]
Thanks @blois!!! This is amazing!

**Comment by nulflux** [comment]
Today ipywidgets Text will no longer work. There is a message about adding two lines to allow external widgets loading but that does not fix the problem.

**Comment by colaboratory-team** [comment]
@nulflux downgrading the ipywidgets version should work for you until we can get a fix out:

`!pip install ipywidgets==7.7.1` and then restart your runtime

**Comment by nulflux** [comment]
That worked, thank you!

**Comment by blois** [comment]
Added some details on the issue in https://github.com/googlecolab/colabtools/issues/3020#issuecomment-1223330253.

**Comment by ammarsaf** [comment]
Already `!pip install ipywidgets==7.7.` but not working today.
