### ISSUE TITLE
Failed to assign a backend FetchError

### ISSUE THREAD

**Issue by DeepLearningAndBreastCancer** [googlecolab/colabtools#65]
Failed to assign a backend FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/assign?authuser=0: 503

**Comment by parap1uie-s** [comment]
Same error.
It seems like the GPU resources has been ran out.
So there is no free GPU resource to be fetched.
And I have no idea about this. Someone know how to deal with?

**Comment by fischman** [comment]
@DeepLearningAndBreastCancer Trying again later should resolve the issue. Sorry for the inconvenience.
@parap1uie-s the URL in the original report is for a CPU runtime, not a GPU one.

**Comment by denfromufa** [comment]
still getting this error:

![image](https://user-images.githubusercontent.com/7870949/36904698-0ebb7670-1df7-11e8-990f-8c86b9a1f34c.png)

**Comment by fischman** [comment]
@denfromufa: thanks for the heads-up.  Should be fixed now. Please confirm.

**Comment by denfromufa** [comment]
@fischman confirming - fixed now!

```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16586242272306038896
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 11297803469
locality {
  bus_id: 1
}
incarnation: 1496199350678444246
physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"
]
```

**Comment by jawadrasool** [comment]
Hi,

I am still getting the same error for the last 16 hours. Can you please suggest something

thanks

**Comment by stabilus** [comment]
ran into the same error. Plus when clicking "Connect" on that error mesagge, a 2nd error message comes up: Sorry, no backends available. Please try again later.

I would imagine that when the first error appears and alerts us that no GPUs are available, clicking Connect would then enable a CPU backend, but instead the 2nd error messages appears.

**Comment by vaibhav198** [comment]
Hi,
I'm getting the same error since last 12 hours. Can anyone help me please

thanks;
![Screenshot from 2020-02-27 09-24-47](https://user-images.githubusercontent.com/25102603/75410807-151b1a00-5943-11ea-9ffa-25b45a501040.png)

**Comment by shafin191** [comment]
Same Error. Cannot connect with my google account. Tried different browsers (Firefox, Chrome). No luck.

**Comment by hayupadhyaya** [comment]
I've suffered from it today. what can I do to solve this?

**Comment by vaibhav198** [comment]
Try after some time, you will get the GPU instance. At the moment, when you
were using the collab, it might be possible that all the free GPU resources
are in use.

Thanks
